title: maguro-osakana.github.io
theme: jekyll-theme-primer

# GoatCounter code を設定すると全ページでアクセス解析が有効になります。
# https://maguroosakana.goatcounter.com/
goatcounter_code: "maguroosakana"

defaults:
  - scope:
      path: ""
    values:
      layout: default
